  - name: Install packages that allow apt to be used over HTTPS
    apt:
      name: "{{ apt_packages }}"
      state: present
      update_cache: yes

  - name: Add an apt signing key for Docker
    apt_key:
      url: "{{ docker_pgp_key }}"
      state: present

  - name: Add apt repository for stable version
    apt_repository:
      repo: deb [arch=amd64] {{ docker_apt_reposity }}
      state: present

  - name: Install docker and its dependecies
    apt: 
      name: "{{ docker_packages }}"
      state: present
      update_cache: yes
    notify:
      - docker status

  - name: Add vagrant user to docker group
    user:
      name: vagrant
      group: docker
  
  - name: Remove swapfile from /etc/fstab
    mount:
      name: "{{ item }}"
      fstype: swap
      state: absent
    with_items: "{{ swap_items }}"

  - name: Disable swap
    command: swapoff -a
    when: ansible_swaptotal_mb > 0
    
  - name: Add an apt signing key for Kubernetes
    apt_key:
      url: "{{ k8s_pgp_key }}"
      state: present

  - name: Adding apt repository for Kubernetes
    apt_repository:
      repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
      state: present
      filename: kubernetes.list

  - name: Install Kubernetes binaries
    apt: 
      name: "{{ k8s_packages }}"
      state: present
      update_cache: yes

  - name: Initialize the Kubernetes cluster using kubeadm
    command: kubeadm init --apiserver-advertise-address="{{ apiserver-advertise-address }}" --apiserver-cert-extra-sans="{{ apiserver-advertise-address }}"  --node-name k8s-master --pod-network-cidr=192.168.0.0/16
  
  - name: Install calico pod network
    become: false
    command: kubectl create -f {{ calico_yaml_url }}

  - name: Generate join command
    command: kubeadm token create --print-join-command
    register: join_command

  - name: Copy join command to local file
    local_action: copy content="{{ join_command.stdout_lines[0] }}" dest="./join-command"